services:
  app:
    build: .
    container_name: PapkiNetFileManager
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/Papki.net/storage
      - ./logs:/Papki.net/logs
    env_file:
      - .env
    restart: unless-stopped
